
FROM tensorflow/tensorflow:2.9.2-gpu

WORKDIR /src

# Copies the trainer code to the docker image.
COPY trainer/* trainer/ 

RUN pip install -r trainer/requirements.txt

# # Sets up the entry point to invoke the trainer.
# # ENTRYPOINT ["python", "-m", "trainer.task"]
